---
title: "DE - Tumor type - unadj for difference - monocle clean"
author: "Sarah Lee"
date: '2022-05-17'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load packages
library(Seurat)
library(SeuratWrappers)
library(tidyverse)
library(ggplot2)
library(scales)
library(patchwork)
library(ggrepel)
library(ReactomePA)
library(org.Hs.eg.db)
library(RColorBrewer)
library(monocle3)
```


```{r}
DefaultAssay(full.integrated_v2) <- "RNA"
```

# Get rid of invariant features
```{r}
summary(rowSums(full.integrated_v2@assays$RNA))
```

```{r}
full.integrated_v2 <- FindVariableFeatures(object = full.integrated_v2, selection.method = "vst", nfeatures = 4000)

# Identify the 10 most highly variable genes
keep <- head(VariableFeatures(full.integrated_v2), 4000)
```

# Make into monocle format
```{r}
cds <- as.cell_data_set(full.integrated_v2)
```

```{r}
cds <- estimate_size_factors(cds)
```

```{r}
# Subset
cds_subset <- cds[keep, ]
```

# Tumor type vs normal
```{r}
colData(cds_subset)$tumortype_v2 <- factor(colData(cds_subset)$Tumor_Categories, levels = c("Non-Tumor", "Astrocytoma", "Embryonal", "Ependymoma",
                                                                              "Glioneuronal/Neuronal", "Glioblastoma", "Schwannoma"))
```

```{r}
table(colData(cds_subset)$tumortype_v2)
```


```{r}
gene_fits2 <- fit_models(cds_subset, model_formula_str = "~tumortype_v2")
```

```{r}
fit_coefs2 <- coefficient_table(gene_fits2)
eval2 <- evaluate_fits(gene_fits2)

table(eval2$status)
```

# Pathways associated with each tumor type differentially expressed genes
```{r}
library(ReactomePA)
```

```{r}
tumor_types <- unlist(unique(tumortype_results2$tumor_cat))

for(i in tumor_types){
  # Get gene ids
  genes <- mapIds(org.Hs.eg.db, 
                  keys = tumortype_results2$gene_id[(tumortype_results2$tumor_cat == i & tumortype_results2$sig %in% "1")], 
                  column = "ENTREZID", 
                  keytype = "SYMBOL", 
                  multiVals = "first")
  genes <- genes[!is.na(genes)]
  
  # Find enriched pathways
  pathways <- enrichPathway(gene = genes)
  pathways_df <- pathways@result
  pathways_df$Description_clean <- gsub("Homo sapiens\r: ", "", pathways_df$Description)
  
}
```

